# ══════════════════════════════════════════════════════════════
# Taskfile.yml - Команды для проекта
# Установка: https://taskfile.dev
# Windows: scoop install task / choco install go-task / winget install Task.Task
# ══════════════════════════════════════════════════════════════
version: "3"

vars:
  PROJECT_ROOT: "{{.ROOT_DIR}}"
  LANGGRAPH_DIR: "packages/langgraph-app"

silent: false

tasks:
  # ══════════════════════════════════════════════════════════════
  # AGENT TESTING (используют скрипты из scripts/)
  # ══════════════════════════════════════════════════════════════

  agent:check:
    desc: "Проверить что агент импортируется и все компоненты работают"
    cmds:
      - uv run --package langgraph-app python {{.LANGGRAPH_DIR}}/scripts/agent_check.py

  agent:invoke:
    desc: "Тест агента с запросом (task agent:invoke -- найди МФЦ)"
    cmds:
      - uv run --package langgraph-app python {{.LANGGRAPH_DIR}}/scripts/agent_invoke.py {{.CLI_ARGS}}

  agent:stream:
    desc: "Тест агента со стримингом (task agent:stream -- найди школу)"
    cmds:
      - uv run --package langgraph-app python {{.LANGGRAPH_DIR}}/scripts/agent_stream.py {{.CLI_ARGS}}

  agent:categories:
    desc: "Тест классификации категорий на примерах"
    cmds:
      - uv run --package langgraph-app python {{.LANGGRAPH_DIR}}/scripts/agent_categories.py

  agent:tools:
    desc: "Показать tools для категории (task agent:tools -- pets)"
    cmds:
      - uv run --package langgraph-app python {{.LANGGRAPH_DIR}}/scripts/agent_tools.py {{.CLI_ARGS}}

  # ══════════════════════════════════════════════════════════════
  # RAG INDEXING
  # ══════════════════════════════════════════════════════════════

  rag:pipeline:
    desc: "Парсинг документов с gu.spb.ru"
    cmds:
      - uv run --package langgraph-app python -m langgraph_app.rag.pipeline

  rag:index:
    desc: "Индексация документов (BM25 + ChromaDB)"
    cmds:
      - uv run --package langgraph-app python -m langgraph_app.rag.indexer

  rag:reindex:
    desc: "Полная переиндексация (удаляет старый индекс)"
    cmds:
      - cmd: Remove-Item -Recurse -Force data\chroma_db -ErrorAction SilentlyContinue
        platforms: [windows]
      - cmd: rm -rf data/chroma_db
        platforms: [linux, darwin]
      - uv run --package langgraph-app python -m langgraph_app.rag.indexer

  rag:all:
    desc: "Полный пайплайн: парсинг + индексация"
    cmds:
      - task: rag:pipeline
      - task: rag:index

  # ══════════════════════════════════════════════════════════════
  # LANGGRAPH
  # ══════════════════════════════════════════════════════════════

  langgraph:dev:
    desc: "Запустить LangGraph Studio в dev режиме"
    dir: "{{.LANGGRAPH_DIR}}"
    cmds:
      # --allow-blocking нужен т.к. torch/transformers делают sync I/O при импорте
      - uv run langgraph dev --allow-blocking

  langgraph:up:
    desc: "Запустить LangGraph Server"
    dir: "{{.LANGGRAPH_DIR}}"
    env:
      # Изолирует blocking операции в отдельные event loops
      BG_JOB_ISOLATED_LOOPS: "true"
    cmds:
      - uv run langgraph up --config langgraph.json

  # ══════════════════════════════════════════════════════════════
  # UI
  # ══════════════════════════════════════════════════════════════

  streamlit:
    desc: "Запустить Streamlit UI"
    dir: packages/streamlit-ui
    cmds:
      - uv run streamlit run src/streamlit_ui/app.py

  # ══════════════════════════════════════════════════════════════
  # BOTS
  # ══════════════════════════════════════════════════════════════

  bot:telegram:
    desc: "Запустить Telegram бота"
    dir: packages/bot-telegram
    cmds:
      - uv run python -m bot_telegram

  bot:max:
    desc: "Запустить MAX бота"
    dir: packages/bot-max
    cmds:
      - uv run python -m bot_max

  # ══════════════════════════════════════════════════════════════
  # DEVELOPMENT
  # ══════════════════════════════════════════════════════════════

  lint:
    desc: "Проверить код с ruff"
    cmds:
      - uv run ruff check .

  lint:fix:
    desc: "Исправить ошибки ruff автоматически"
    cmds:
      - uv run ruff check . --fix

  format:
    desc: "Форматировать код с ruff"
    cmds:
      - uv run ruff format .

  typecheck:
    desc: "Проверка типов (pyright)"
    cmds:
      - uv run pyright

  # ══════════════════════════════════════════════════════════════
  # DEPENDENCIES
  # ══════════════════════════════════════════════════════════════

  sync:
    desc: "Синхронизировать все зависимости"
    cmds:
      - uv sync --all-packages

  lock:
    desc: "Обновить lock файл"
    cmds:
      - uv lock

  add:
    desc: "Добавить зависимость (task add -- package-name)"
    cmds:
      - uv add {{.CLI_ARGS}}

  # ══════════════════════════════════════════════════════════════
  # DOCKER
  # ══════════════════════════════════════════════════════════════

  docker:build:
    desc: "Собрать Docker образы"
    cmds:
      - docker compose build

  docker:up:
    desc: "Запустить все сервисы в Docker"
    cmds:
      - docker compose up -d

  docker:down:
    desc: "Остановить Docker сервисы"
    cmds:
      - docker compose down

  docker:logs:
    desc: "Показать логи Docker"
    cmds:
      - docker compose logs -f

  # ══════════════════════════════════════════════════════════════
  # UTILITIES
  # ══════════════════════════════════════════════════════════════

  clean:
    desc: "Очистить кэш и временные файлы"
    cmds:
      - cmd: Remove-Item -Recurse -Force .pytest_cache, .ruff_cache, __pycache__, .mypy_cache, data/memory.db -ErrorAction SilentlyContinue
        platforms: [windows]
      - cmd: rm -rf .pytest_cache .ruff_cache __pycache__ .mypy_cache data/memory.db
        platforms: [linux, darwin]

  help:
    desc: "Показать все доступные команды"
    cmds:
      - task --list

  # ══════════════════════════════════════════════════════════════
  # DEFAULT
  # ══════════════════════════════════════════════════════════════

  default:
    desc: "Показать справку"
    cmds:
      - task help
